### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by zt3ph4n** [URSec/Ombro#1]
<title></title>

Regards

**Comment by ethanjohnson89** [comment]
Hi zt3ph4n,

Our group is continuing to work on related projects in the area of compiler-enforced hypervisor security, but we are not currently working on Ombro _per se_ at the moment. We hope to build on it in the future with further exploration of SVA and virtual-instruction-set computing as applied to hypervisors, but for the time being, the published source code here serves primarily as a public record of what we've already done in our ATC '22 paper.

Are you interested in doing your own work in this area, and/or building on the open-source Ombro code? If so, I'd be happy to discuss Ombro and how to work with its code!

Ethan Johnson
